stages:
  - semgrep-scan
  - build
  - trivy-scan
  - deploy


variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE/calc:latest

security_scan_semgrep:
  stage: semgrep-scan
  image: returntocorp/semgrep:latest
  script:
    - semgrep --config auto --json --output semgrep_report.json $CI_PROJECT_DIR
  artifacts:
    paths:
      - semgrep_report.json
    when: always
  only:
    - main

build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  only:
    - main

security_scan_trivy:
  stage: trivy-scan
  image: docker:20.10.16-dind
  services:
    - docker:20.10.16-dind
  script:
    - apk add --no-cache curl  
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh  
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - ./bin/trivy image --format json --output trivy_report.json $IMAGE_NAME
  artifacts:
    paths:
      - trivy_report.json
    when: always
  only:
    - main

deploy:
  stage: deploy
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - apk add curl
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker pull $IMAGE_NAME
    - docker run -d -p 8000:8000 --name calculator $IMAGE_NAME
    - sleep 10
    - curl -L http://docker:8000/
    - curl -L "http://docker:8000/add?a=1&b=2"
    - curl -L "http://docker:8000/divide?a=1&b=0"
  only:
    - main